# Generated by Django 3.2 on 2021-04-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=30)),
                ('Thumbnail', models.ImageField(blank=True, upload_to='')),
                ('Article', models.TextField(max_length=1000)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotTopicArticle',
            fields=[
                ('articleattributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ArticleApp.articleattributes')),
            ],
            bases=('ArticleApp.articleattributes',),
        ),
        migrations.CreateModel(
            name='OfficialArticle',
            fields=[
                ('articleattributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ArticleApp.articleattributes')),
            ],
            bases=('ArticleApp.articleattributes',),
        ),
        migrations.CreateModel(
            name='TransfersArticle',
            fields=[
                ('articleattributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ArticleApp.articleattributes')),
            ],
            bases=('ArticleApp.articleattributes',),
        ),
    ]
