# Generated by Django 3.2 on 2021-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0002_alter_articleattributes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleattributes',
            name='Article',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='articleattributes',
            name='Thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
